//accountActions
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

//subjectActions
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const FETCH_SUBJECT = 'FETCH_SUBJECT'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'

//buildingActions
export const ADD_BUILDING = 'ADD_BUILDING'
export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const DELETE_BUILDING = 'DELETE_BUILDING'
export const ADD_ROOM = 'ADD_ROOM'

//courseActions
export const ADD_COURSE = 'ADD_COURSE'
export const FETCH_COURSES = 'FETCH_COURSES'
export const DELETE_COURSE = 'DELETE_COURSE'

//timeSlotActions
export const ADD_TIME_SLOT = 'ADD_TIME_SLOT'
export const FETCH_TIME_SLOTS = 'FETCH_TIME_SLOTS'
export const DELETE_TIME_SLOT = 'DELETE_TIME_SLOT'

//semesterCourseActions
export const ADD_SEMESTER_COURSE = 'ADD_SEMESTER_COURSE'
export const FETCH_SEMESTER_COURSES = 'FETCH_SEMESTER_COURSES'
export const DELETE_SEMESTER_COURSE = 'DELETE_SEMESTER_COURSE'
export const UPDATE_SEMESTER_COURSE = 'UPDATE_SEMESTER_COURSE'