//subjects
import {MATH, ECON, BIO, COMP, HIST } from "./universityDataTypes"
//course names
import { ALGEBRA, STATISTICS, MICROECONOMICS, MACROECONOMICS, CELL_BIO, HUMAN_BIO,
FOUNDATIONS_OF_BIO, ALGORITHMS, DATA_STRUCTURES, DISCRETE_STUCTURES, CANADIAN_SOCIAL_HIST,
TOWN_LIFE_MIDDLE_AGES, AMERICAN_SOCIAL_MOVEMENTS_60S } from "./universityDataTypes"
//course descriptions
import { ALGEBRA_DESC, STATISTICS_DESC, MICROECONOMICS_DESC,
MACROECONOMICS_DESC, CELL_BIO_DESC, HUMAN_BIO_DESC, FOUNDATIONS_OF_BIO_DESC,
ALGORITHMS_DESC, DATA_STRUCTURES_DESC, DISCRETE_STUCTURES_DESC, CANADIAN_SOCIAL_HIST_DESC,
TOWN_LIFE_MIDDLE_AGES_DESC, AMERICAN_SOCIAL_MOVEMENTS_60S_DESC } from "./universityDataTypes"

//buildings
import { BUILDING_1, BUILDING_2 } from "./universityDataTypes"

//rooms in buildings
import { BUILDING_1_ROOM_1, BUILDING_1_ROOM_2,BUILDING_1_ROOM_3, BUILDING_2_ROOM_1, BUILDING_2_ROOM_2,
    BUILDING_2_ROOM_3, BUILDING_2_ROOM_4 } from "./universityDataTypes"

//room capacity
import { BUILDING_1_ROOM_1_CAPACITY, BUILDING_1_ROOM_2_CAPACITY, BUILDING_1_ROOM_3_CAPACITY, BUILDING_2_ROOM_1_CAPACITY,
    BUILDING_2_ROOM_2_CAPACITY, BUILDING_2_ROOM_3_CAPACITY, BUILDING_2_ROOM_4_CAPACITY} from "./universityDataTypes"

export const allCourses = [{name: ALGEBRA, subject: MATH, desc: ALGEBRA_DESC}, {name: STATISTICS, subject: MATH, desc: STATISTICS_DESC},
{name: MICROECONOMICS, subject: ECON, desc: MICROECONOMICS_DESC}, {name: MACROECONOMICS, subject: ECON, desc: MACROECONOMICS_DESC},
{name: CELL_BIO, subject: BIO, desc: CELL_BIO_DESC}, {name: HUMAN_BIO, subject: BIO, desc: HUMAN_BIO_DESC}, 
{name: FOUNDATIONS_OF_BIO, subject: BIO, desc: FOUNDATIONS_OF_BIO_DESC},
{name: ALGORITHMS, subject: COMP, desc: ALGORITHMS_DESC}, {name: DATA_STRUCTURES, subject: COMP, desc: DATA_STRUCTURES_DESC},
{name: DISCRETE_STUCTURES, subject: COMP, desc: DISCRETE_STUCTURES_DESC}, 
{name: CANADIAN_SOCIAL_HIST, subject: HIST, desc: CANADIAN_SOCIAL_HIST_DESC}, 
{name: TOWN_LIFE_MIDDLE_AGES, subject: HIST, desc: TOWN_LIFE_MIDDLE_AGES_DESC}, 
{name: AMERICAN_SOCIAL_MOVEMENTS_60S, subject: HIST, desc: AMERICAN_SOCIAL_MOVEMENTS_60S_DESC}]

export const allLocations = [{name: BUILDING_1, roomNum: BUILDING_1_ROOM_1, capacity: BUILDING_1_ROOM_1_CAPACITY},
    {name: BUILDING_1, roomNum: BUILDING_1_ROOM_2, capacity: BUILDING_1_ROOM_2_CAPACITY},
    {name: BUILDING_1, roomNum: BUILDING_1_ROOM_3, capacity: BUILDING_1_ROOM_3_CAPACITY},
    {name: BUILDING_2, roomNum: BUILDING_2_ROOM_1, capacity: BUILDING_2_ROOM_1_CAPACITY},
    {name: BUILDING_2, roomNum: BUILDING_2_ROOM_2, capacity: BUILDING_2_ROOM_2_CAPACITY},
    {name: BUILDING_2, roomNum: BUILDING_2_ROOM_3, capacity: BUILDING_2_ROOM_3_CAPACITY},
    {name: BUILDING_2, roomNum: BUILDING_2_ROOM_4, capacity: BUILDING_2_ROOM_4_CAPACITY}]